import {
	index,
	integer,
	jsonb,
	pgTable,
	primaryKey,
	text,
	timestamp,
} from "drizzle-orm/pg-core";
import type { Field, FormDef } from "@/lib/forms/types";
import { user } from "./auth-schema";

// Better Auth tables (generated by `pnpm auth:generate`).
export * from "./auth-schema";

export const forms = pgTable(
	"forms",
	{
		id: text("id").primaryKey(),
		ownerId: text("owner_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		title: text("title").notNull(),
		description: text("description").notNull().default(""),
		fields: jsonb("fields").$type<Field[]>().notNull(),
		// Content language → drives public-page direction (LTR/RTL).
		locale: text("locale").notNull().default("en"),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => [index("forms_owner_id_idx").on(t.ownerId)],
);

export const responses = pgTable(
	"responses",
	{
		id: text("id").primaryKey(),
		formId: text("form_id")
			.notNull()
			.references(() => forms.id, { onDelete: "cascade" }),
		answers: jsonb("answers")
			.$type<Record<string, string | string[]>>()
			.notNull(),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => [index("responses_form_id_idx").on(t.formId)],
);

// Abuse / cost protection (Layer 7) — Postgres-backed counters + prompt cache.
// Single-statement ON CONFLICT upserts keep this on the neon-http driver.
export const usage = pgTable(
	"usage",
	{
		day: text("day").notNull(), // "YYYY-MM-DD"
		scope: text("scope").notNull(), // "global" | "ip" | "user"
		key: text("key").notNull(), // "all" | <ip> | <userId>
		count: integer("count").notNull().default(0),
	},
	(t) => [primaryKey({ columns: [t.day, t.scope, t.key] })],
);

export const generationCache = pgTable("generation_cache", {
	promptHash: text("prompt_hash").primaryKey(),
	formDef: jsonb("form_def").$type<FormDef>().notNull(),
	locale: text("locale").notNull().default("en"),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
});

export type FormRow = typeof forms.$inferSelect;
export type FormInsert = typeof forms.$inferInsert;
export type ResponseRow = typeof responses.$inferSelect;
export type ResponseInsert = typeof responses.$inferInsert;
