import { getCloudflareContext } from "@opennextjs/cloudflare";

/**
 * The single place the app reads Cloudflare bindings and secrets.
 *
 * On Workers, `env` is provided per-request — never capture it at module scope.
 * Call `getEnv()` inside request handlers, Server Components, or Route Handlers.
 * The `CloudflareEnv` type is generated by `pnpm cf-typegen` from wrangler.jsonc.
 */
export function getEnv(): CloudflareEnv {
	return getCloudflareContext().env;
}
